name: layer_contracts
description: Http layer contracts for Dart clients
version: 0.1.0
repository: https://github.com/easy-http/layer-contracts-dart

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
